name: Run Python Script

on:
  workflow_dispatch:

env:
  account_sid: ${{ sccrets.ACCOUNT_SID}}
  auth_token: ${{ sccrets.AUTH_TOKEN}}
  twilio_number: ${{ secrets.TWILIO_NUMBER}}
  my_number: ${{ sccrets.MY_PHONE_NUMBER}}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Python Script
        run: |
          python -m pip install requests
          python -m pip install twilio
          python mta_train_notify.py
          

          

