name: Run Python Script

on:
  workflow_dispatch:
  schedule:
      - cron: '30 10 * * *' #minute, hour, day, day of month, day of week
            

env:
  account_sid: ${{ secrets.ACCOUNT_SID}}
  auth_token: ${{ secrets.AUTH_TOKEN }}
  twilio_number: ${{ secrets.TWILIO_NUMBER }}
  my_phone_number: ${{ secrets.MY_PHONE_NUMBER }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ secrets.account_sid}}'
      - run: echo 'Hi ${{ env.auth_token}}'
      
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install requests
          python -m pip install twilio
          python -m pip install python-dotenv

      - name: Run Python Script

        run: |
          python mta_train_notify.py
