name: Run Python Script

on:
  workflow_dispatch:

env:
  ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
  MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install requests
          python -m pip install twilio
          python -m pip install python-dotenv

      - name: Run Python Script
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
          MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}
        run: |
          python mta_train_notify.py
