name: Run Python Script

on:
  workflow_dispatch:

env:
  account_sid: ${{ vars.ACCOUNT_SID }}
  auth_token: ${{ vars.AUTH_TOKEN }}
  twilio_number: ${{ vars.TWILIO_NUMBER }}
  my_phone_number: ${{ vars.MY_PHONE_NUMBER }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ env.account_sid}}'
      - run: echo 'Hi ${{ env.twilio_number}}'
      
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install requests
          python -m pip install twilio
          python -m pip install python-dotenv

      - name: Run Python Script
        env:
          account_sid: ${{ vars.ACCOUNT_SID }}
          auth_token: ${{ vars.AUTH_TOKEN }}
          twilio_number: ${{ vars.TWILIO_NUMBER }}
          my_phone_number: ${{ vars.MY_PHONE_NUMBER }}
        run: |
          python mta_train_notify.py
